### ISSUE TITLE
[返信機能] SDKから投稿されたUserCommentを保存する

### ISSUE THREAD

**Issue by himaratsu** [meyasubaco/user-api#37]
## 処理の流れ概要

* 送られてくる内容は、これまで通りの情報 + Thread 情報
 * os
 * model
 * mail
 * appVersion
 * content
 * thread_id :new: 
* thread_id
 * 「どのスレッドに対してのコメントか」を示すためのid
 * 新規投稿（ユーザーからの最初の質問）の場合は thread_in = null となる

### アプリユーザーの作成

初回起動時のタイミングで、SDK によって AppliUser を作成する。

* AppliUserは以下の情報を持つ
 * UUIDベースのランダムなid
 * pushToken
 * os
 * model
* これを受け付けてデータベースに保存しておく
* ヘルプの閲覧、コメント投稿のAPIをたたく際にはこの AppliUser を付加して送信する

### コメントの投稿

* thread_id があるか確認
* あれば Thread に紐づく形で UserComment を新規に作成して保存
* なければ Thread を作成し、それに紐づく形で UserComment を作って保存
 * Thread は以下の情報を持つ
  * app
  * appliUser
  * lastCommentContent :star: 
  * lastCommentUpdatetime :star: 
  * lastCommentPoster ( "developer" or "user" の文字列) :star: 
  * lastDeveloperShowTime
  * lastUserShowTime :star: 
  * developerReplied ( Boolean ) 
* Thread の最終更新系の情報（ :star: ）をアップデートする

## 必要なAPI

* AppliUser の登録
* UserComment の登録

**Comment by shoma2da** [comment]
APIはできたので、クローズで良いかな？

**Comment by himaratsu** [comment]
it closed
